[tool.ruff]
required-version = ">=0.12.10"
line-length = 142
target-version = "py313"
fix = false
include = ["src/**/*.py", "src/**/*.wsgi"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "BLE001",  # Ignore except Exception
    "ERA001",  # Found commented-out code
    "TRY300",  # Consider moving this statement to an `else` block of the `try` statement
    "G004",    # Logging statement uses f-string
    "TRY401",  # Redundant exception object included in `logging.exception` call (we have own exception logic)
    "TD003",   # Missing issue link for this TODO
    "FIX002",  # Line contains TODO, consider resolving the issue
    "FBT001",  # Boolean-typed positional argument in function definition (enable True/False parameters)
    "FBT002",  # Boolean default positional argument in function definition
]

[tool.ruff.lint.per-file-ignores]
"docker/gunicorn_conf.py" = ["INP001", "S104"]
"src/collectors/run.py" = ["E402"]
"src/presenters/run.py" = ["E402"]
"src/publishers/run.py" = ["E402"]
"/Users/filiporlicky/PycharmProjects/FlaskProjectPTZ/zkusmo_dva.py" = ["F401"]

[tool.ruff.format]
line-ending = "lf"
docstring-code-format = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pylint]
max-args = 12
max-branches = 20
max-returns = 10
max-statements = 80

[tool.ruff.lint.mccabe]
max-complexity = 20